"""Raspberry Pi request from ESP32"""

FIRST_SLAVE_REQUEST_ADDRESS = 0x00
LAST_SLAVE_REQUEST_ADDRESS = 0x9F

# Encoder "registers"
REQUEST_ALL_ENCODER_ADDRESS = 0x10
REQUEST_INDIVIDUAL_ENCODER_FIRST_ADDRESS = 0x11

# Motor current sense "registers"
REQUEST_ALL_MOTOR_CURRENT_ADDRESS = 0x20
REQUEST_INDIVIDUAL_MOTOR_CURRENT_FIRST_ADDRESS = 0x21

# Motor stall status "registers"
REQUEST_ALL_MOTOR_STALL_ADDRESS = 0x30

# Motor disconnect status "registers"
REQUEST_ALL_MOTOR_DISCONNECT_ADDRESS = 0x31

# IMU "registers"
REQUEST_IMU_ACCELERATION_ADDRESS = 0x40
REQUEST_IMU_GYROSCOPE_ADDRESS = 0x41
REQUEST_IMU_MAGNETIC_ADDRESS = 0x42
REQUEST_IMU_QUATERNION_ADDRESS = 0x43

# Battery "registers"
REQUEST_BATTERY_VOLTAGE_ADDRESS = 0x50


"""Raspberry Pi send command to ESP32"""

FIRST_SLAVE_COMMAND_ADDRESS = 0xA0
LAST_SLAVE_COMMAND_ADDRESS = 0xFF

# Motor operation mode "registers"
SET_MOTOR_MODE_ADDRESS = 0xA0

# Standard motor data "registers"
SET_MOTOR_STANDARD_DATA_ADDRESS = 0xA1
SET_MOTOR_INDIVIDUAL_STANDARD_DATA_FIRST_ADDRESS = 0xA2

# Motor direction "registers"
SET_MOTOR_DIRECTION_ADDRESS = 0xA6
SET_MOTOR_INDIVIDUAL_DIRECTION_FIRST_ADDRESS = 0xA7

# Motor speed "registers"
SET_MOTOR_SPEED_ADDRESS = 0xAB
SET_MOTOR_INDIVIDUAL_SPEED_FIRST_ADDRESS = 0xAC

# Robot "registers"
SET_ROBOT_DIRECTION_ADDRESS = 0xB0
SET_ROBOT_COMMON_SPEED_ADDRESS = 0xB2


"""Bit positions"""

# Motor operation mode
MOTOR_MODE_SAFETY_BIT_0_POSITION = 0
MOTOR_MODE_SAFETY_BIT_1_POSITION = 1

MOTOR_MODE_SPEED_BIT_0_POSITION = 2
MOTOR_MODE_SPEED_BIT_1_POSITION = 3

MOTOR_MODE_ENABLE_BIT_POSITION = 4

# Other motor registers
MOTOR_NUMBER_OF_BITS_PER_MOTOR = 2